[package]
name = "minihttp"
version = "0.1.0"
authors = ["Alexey Popravka <alexey.popravka@horsedevel.com>"]

[dependencies]

futures = "0.1.7"
httparse = "1.1.2"
tokio-core = "0.1.0"
tk-bufstream = "0.2.3"
netbuf = "0.3.7"
quick-error = "1.1.0"
matches = "0.1.4"
log = "0.3.6"
url = "1.2.3"
sha1 = "0.2.0"

# for curl-rs and "simple" interface (may be move to another crate?)
futures-cpupool = "0.1.2"
abstract-ns = "0.2.1"
argparse = "0.2.1"
env_logger = "0.3.5"
ns-std-threaded = "0.1.0"

[features]
default = ["sendfile"]
sendfile = []

[dev-dependencies]
env_logger = "0.3.5"
argparse = "0.2.1"
futures-cpupool = "0.1.2"
time = "0.1.35"
tk-sendfile = "0.3.0"

[[bin]]
name = "curl-rs"
path = "src/bin/curl.rs"
